// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZEnUxvuOw5OQkOX8B3t_7w3cd36f1bNI',
    appId: '1:565370015678:web:975bf4e7f5600f884533ef',
    messagingSenderId: '565370015678',
    projectId: 'fir-notification-53606',
    authDomain: 'fir-notification-53606.firebaseapp.com',
    storageBucket: 'fir-notification-53606.appspot.com',
    measurementId: 'G-68RZCJL0K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCALGtyKVK67DQwUwqzYfrM9ZHIAenwaXQ',
    appId: '1:565370015678:android:d408d62f9810ab3d4533ef',
    messagingSenderId: '565370015678',
    projectId: 'fir-notification-53606',
    storageBucket: 'fir-notification-53606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuUEbKfUoG5VdvwPIRfxb_17RYsbxzhqM',
    appId: '1:565370015678:ios:7148b291d6a159b14533ef',
    messagingSenderId: '565370015678',
    projectId: 'fir-notification-53606',
    storageBucket: 'fir-notification-53606.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuUEbKfUoG5VdvwPIRfxb_17RYsbxzhqM',
    appId: '1:565370015678:ios:7148b291d6a159b14533ef',
    messagingSenderId: '565370015678',
    projectId: 'fir-notification-53606',
    storageBucket: 'fir-notification-53606.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZEnUxvuOw5OQkOX8B3t_7w3cd36f1bNI',
    appId: '1:565370015678:web:5792913c1ce1af774533ef',
    messagingSenderId: '565370015678',
    projectId: 'fir-notification-53606',
    authDomain: 'fir-notification-53606.firebaseapp.com',
    storageBucket: 'fir-notification-53606.appspot.com',
    measurementId: 'G-5VPCXZZWY4',
  );
}
